### ISSUE TITLE
conflicting info for `ExpressionData` in `/api/work-preview` response vs. openapi doc

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-instance-frischmuth#132]
for the `/api/work-preview/` response shape, the openapi doc says `results[].expression_data[].edition_type` and `results[].expression_data[].language` have type `string`, however the actual api endpoint returns an array.

see [`ExpressionData` schema](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/swagger/schema/swagger-ui/#model-ExpressionData)

see response:

```bash
curl https://frischmuth-dev.acdh-dev.oeaw.ac.at/api/work-preview/ | jq '.results[].expression_data[].edition_type'
```

```bash
curl https://frischmuth-dev.acdh-dev.oeaw.ac.at/api/work-preview/ | jq '.results[].expression_data[].language'
```

**Comment by koeaw** [comment]
@stefanprobst This is indeed a known issue, see [this comment](https://gitlab.oeaw.ac.at/acdh-ch/frischmuth/backend/apis-instance-frischmuth/-/issues/122#note_13534) from end of May.

**Comment by stefanprobst** [comment]
the issue you linked to is already closed - does that mean this should be fixed with the next backend deployment?

**Comment by koeaw** [comment]
> the issue you linked to is already closed - does that mean this should be fixed with the next backend deployment?

No, it means the issue is done (the core issue, the issue at hand was solved) and needs to be followed up with a new issue.  [Which lives here.](https://gitlab.oeaw.ac.at/acdh-ch/frischmuth/backend/apis-instance-frischmuth/-/issues/157)

Same for issues labelled "DONE", incidentally, which I only keep open because I need to be able to differentiate "recently closed" issues from the rest of them on the board.

**Comment by stefanprobst** [comment]
i just want to know which issue to subscribe to to get notified when this is solved. i guess that's https://gitlab.oeaw.ac.at/acdh-ch/frischmuth/backend/apis-instance-frischmuth/-/issues/157.
